# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 07:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('area_of_interest', models.TextField(blank=True, null=True)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('display_picture', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('short_description', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_info.College')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_info.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(blank=True, choices=[('study', 'study'), ('project', 'project'), ('paper', 'paper'), ('patent', 'patent')], max_length=250, null=True)),
                ('topic', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='research_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor_info.ResearchWork'),
        ),
    ]
