# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchwork',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
