# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_info', '0003_professor_short_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Research',
            new_name='ResearchWork',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='research',
            new_name='research_work',
        ),
    ]
