# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_info', '0004_auto_20170121_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='research_interest',
            new_name='area_of_interest',
        ),
    ]
