# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_info', '0006_auto_20170124_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
