# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor_info', '0010_auto_20170127_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor_info.College'),
        ),
    ]
