# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_info', '0012_auto_20170127_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='professor_id',
            new_name='id',
        ),
    ]
